name: CheckHomeworks
on:
  workflow_dispatch:
  push:
  pull_request:
  watch:
    types: [ started ]
  schedule:
    - cron: 45 22 * * *

jobs:
  HomeworkCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
          python-version: '3.9.12'
    - name: 'Install dependencies'
      run: python3 -m pip install --upgrade pip

    - name: 'install libs'
      run: pip3 install requests 

    - name: StratCheckHomework
      env:
        ZJU_USERNAME: ${{ secrets.ZJU_USERNAME }}
        ZJU_PASSWORD: ${{ secrets.ZJU_PASSWORD }}

        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}

        FSKEY: ${{ secrets.FSKEY }}

        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}

        PUSH_KEY: ${{ secrets.PUSH_KEY }}

        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_PROXY_HOST: ${{ secrets.TG_PROXY_HOST }}
        TG_PROXY_PORT: ${{ secrets.TG_PROXY_PORT }}
        TG_PROXY_AUTH: ${{ secrets.TG_PROXY_AUTH }}

      run: python3 GetDDL.py
